name: HammerACM
main: fernanACM\HammerACM\HammerACM
version: 1.0.0
api: 5.3.0
author: fernanACM
description: A simple hammer that breaks 3x3. For PocketMine-MP 5.0 servers only
website: https://github.com/fernanACM

commands:
  hammeracm:
    description: "HammerACM by fernanACM"
    permission: hammeracm.cmd
    aliases: ["hammer"]

permissions:
  hammeracm.cmd:
    default: op
  hammeracm.use:
    default: op