#   _   _                                                    _       ____   __  __ 
#  | | | |   __ _   _ __ ___    _ __ ___     ___   _ __     / \     / ___| |  \/  |
#  | |_| |  / _` | | '_ ` _ \  | '_ ` _ \   / _ \ | '__|   / _ \   | |     | |\/| |
#  |  _  | | (_| | | | | | | | | | | | | | |  __/ | |     / ___ \  | |___  | |  | |
#  |_| |_|  \__,_| |_| |_| |_| |_| |_| |_|  \___| |_|    /_/   \_\  \____| |_|  |_|
#               by fernanACM
# A simple hammer that breaks 3x3. For PocketMine-MP 5.0 servers only

# DO NOT TOUCH!
config-version: "1.0.0"

# Prefix plugin
Prefix: "&l[&bHammerACM&f]&8»&r "

# ==(CONFIGURATION)==
Settings:
  # ==(WORLD MANAGER)==
  # Enable and disable the hammer for worlds you 
  # add to "whitelist" or "blacklist" modes
  WorldManager:
    # Valid modes:
    # - whitelist
    # - blacklist
    mode: whitelist
    # Add the names of worlds that are in the whitelist
    worlds-whitelist:
      - "world"
      - "world-2"
      - "ACM"
    # Add the names of worlds that are in the blacklist
    worlds-blacklist:
      - "MinePvP"
      - "ZonePvP"

# ==(HAMMER)==
# Use this for color '&'
Hammer:
  item-name: "&r&l&bHammerACM"
  item-lore: "&r&cby: fernanACM"

Messages:
  success:
    successfully-delivered: "&aThe Hammer has been successfully delivered!"
  error:
    inventory-full: "&cYour inventory is full!"